/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface CalendarBack {}
  interface CalendarBackAttributes extends StencilHTMLAttributes {}

  interface CalendarMonth {}
  interface CalendarMonthAttributes extends StencilHTMLAttributes {}

  interface DatePicker {}
  interface DatePickerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'CalendarBack': Components.CalendarBack;
    'CalendarMonth': Components.CalendarMonth;
    'DatePicker': Components.DatePicker;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'calendar-back': Components.CalendarBackAttributes;
    'calendar-month': Components.CalendarMonthAttributes;
    'date-picker': Components.DatePickerAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCalendarBackElement extends Components.CalendarBack, HTMLStencilElement {}
  var HTMLCalendarBackElement: {
    prototype: HTMLCalendarBackElement;
    new (): HTMLCalendarBackElement;
  };

  interface HTMLCalendarMonthElement extends Components.CalendarMonth, HTMLStencilElement {}
  var HTMLCalendarMonthElement: {
    prototype: HTMLCalendarMonthElement;
    new (): HTMLCalendarMonthElement;
  };

  interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {}
  var HTMLDatePickerElement: {
    prototype: HTMLDatePickerElement;
    new (): HTMLDatePickerElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'calendar-back': HTMLCalendarBackElement
    'calendar-month': HTMLCalendarMonthElement
    'date-picker': HTMLDatePickerElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'calendar-back': HTMLCalendarBackElement;
    'calendar-month': HTMLCalendarMonthElement;
    'date-picker': HTMLDatePickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
